### PR TITLE
check module account is exist

### PR DESCRIPTION
**Pull request by ThanhNhann**
Closes: #622

## Author's Checklist

I have...

- [ ] Run and PASSED locally all GAIA integration tests
- [ ] If the change is contentful, I either:
    - [ ] Added a new unit test OR 
    - [ ] Added test cases to existing unit tests
- [ ] OR this change is a trivial rework / code cleanup without any test coverage

If skipped any of the tests above, explain.

## Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] manually tested (if applicable)
- [ ] confirmed the author wrote unit tests for new logic
- [ ] reviewed documentation exists and is accurate

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes? 
  - [ ] Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`?
  - [ ] This pull request updates existing proto field values (and require a backend and frontend migration)? 
  - [ ] Does this pull request change existing proto field names (and require a frontend migration)?
  How is the feature or change documented? 
      - [ ] not applicable
      - [ ] jira ticket `XXX` 
      - [ ] specification (`x/<module>/spec/`) 
      - [ ] README.md 
      - [ ] not documented

### CODE REVIEW

**Comment by sampocs** [comment]
Can you give some more details on the error that you saw in the simulation tests? From briefly eyeballing it, it looks like this is only called when the chain is started up for the first time, and I think the address' are also deterministic so setting an account that already exists would just override it?

Curious to get @riley-stride's opinion as he's most familiar with this code

**Comment by ThanhNhann** [comment]
Yeah, when I code for simulation test in the case of `TestAppImportExport`, it will always fail because you have to start a new app, and I see that, the error is because we had checked the existing module account. Code for simulation test is below:
https://github.com/notional-labs/stride/blob/716a2d449374f56c7544174e923b75a5c390a836/app/sim_test.go#L83

**Comment by riley-stride** [comment]
> when I code for simulation test in the case of `TestAppImportExport`, it will always fail because you have to start a new app, and I see that, the error is because we don't have a check the existing module account so that it fails for the test after. This test simulates an upgrade chain work with export genesis from the old app and import to the new app. The code for simulation test with update checking is below: https://github.com/notional-labs/stride/blob/716a2d449374f56c7544174e923b75a5c390a836/app/sim_test.go#L83

Can you point us to the line that breaks in the sim tests? When do we create a module account twice?

**Comment by ThanhNhann** [comment]
Hi @riley-stride, full code for this fail test is in this function https://github.com/notional-labs/stride/blob/cd4d171f8492d42956a933c2e679eaa1bea1e195/app/sim_test.go#L84
Steps to run:
  - `make test-sim-import-export` and will show the fail like image below 
  Screenshot 2023-02-22 at 12 36 57
  - Run the line below failed notification in the image, in this case is: `go test ./app -run TestAppImportExport -Enabled=true -NumBlocks=10 -Genesis= -Verbose=true -Commit=true -Seed=7 -Period=2 -ExportParamsPath /var/folders/5y/7n2nyf8x5799th2r_zmw58x00000gn/T/sim-logs-1372263546/sim_params-7.json -ExportStatePath /var/folders/5y/7n2nyf8x5799th2r_zmw58x00000gn/T/sim-logs-1372263546/sim_state-7.json -v -timeout 24h`  and it's will show the error like image below 
  
Screenshot 2023-02-22 at 12 41 07

Insight: 
- The image above show that their are some key/value pairs different with `app` and  `newapp`, 
- I debuged and record all the moduleAccount address in https://github.com/notional-labs/stride/blob/nhan%2Ffail_simualtion_test/app/test.json for the app and https://github.com/notional-labs/stride/blob/nhan%2Ffail_simualtion_test/app/test2.json for the newapp, and see that three accounts seted up by https://github.com/notional-labs/stride/blob/cd4d171f8492d42956a933c2e679eaa1bea1e195/x/mint/genesis.go#L11 will be make a fail. 
- In the file `test.json`, we can check that there are total `925` accounts were created with the max id is `924` and the id for three accounts above are `922,923,924`, after that I also check for file `test2.json` and see that, there are also total `925` accounts were created but with max id is `927` and the id for three accounts above is `925,926,927` and don't have id `922,923,924`, and you know what, the address of accounts `925,926,927` in `test2.json` are the same with accounts `922,923,924` in `test.json`, in this case, I think it mean when we run new app with genesis exported from old app, the information of three accounts above will be added more, not update like another accounts because we don't have a check exist for them. So I added it and run ok now, if you have any questions, feel free to ask, thank!

**Pull request closed without merging**
