### PR TITLE
chore: sdk and tendermint, don't use the debug sdk

### PR DESCRIPTION
**Pull request by faddat**
## Context and purpose of the change

Part of our code cleanup effort:

* discontinue use of the debug sdk branch
* bump tendermint to v0.34.21
* remove unneded starport replace

## Author's Checklist

I have...

- [ ] Run and PASSED locally all GAIA integration tests
- [ ] If the change is contentful, I either:
    - [ ] Added a new unit test OR 
    - [ ] Added test cases to existing unit tests
- [ ] OR this change is a trivial rework / code cleanup without any test coverage

If skipped any of the tests above, explain.

## Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] manually tested (if applicable)
- [ ] confirmed the author wrote unit tests for new logic
- [ ] reviewed documentation exists and is accurate

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes? 
  - [ ] Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`?
  - [ ] This pull request updates existing proto field values (and require a backend and frontend migration)? 
  - [ ] Does this pull request change existing proto field names (and require a frontend migration)?
  How is the feature or change documented? 
      - [ ] not applicable
      - [ ] jira ticket `XXX` 
      - [ ] specification (`x/<module>/spec/`) 
      - [ ] README.md 
      - [ ] not documented

### CODE REVIEW

**Comment by Highlander-maker** [comment]
I have ran this on my validator after seeing some strange logs. See below

Screenshot 2022-09-18 at 16 22 52

I reached out to @faddat  and we have used this branch on my mainnet validator and it is working great. The bad logs are now gone. This is a non-state breaking upgrade so it can be merged right away. :).

**Comment by asalzmann** [comment]
The only change we have in our "debug" sdk is basically this: https://github.com/cosmos/cosmos-sdk/pull/11960

Once this is merged, we could switch over to the stock sdk, but we're making some changes to the distribution module so we're going to have to switch back over to our version soon. It might make more sense to use a cleaner tag name?

Is there a benefit of changing back to the standard sdk? @Highlander-maker do you know why this branch resolved your issues?

**Comment by asalzmann** [comment]
@faddat can we bump tendermint without bumping the sdk?

**Comment by Highlander-maker** [comment]
I've logged in to node and it's sad to say after some more monitoring we are still receiving these crazy large logs after some blocks being produced. 

I will take more notes tomorrow and discuss with @faddat. Apologies for the late update.

**Comment by asalzmann** [comment]
Can you send me one of the logs? Also happy to chat offline.

**Comment by faddat** [comment]
Hey guys, the right way to do things would be to bump tendermint, and if you want to use a modified SDK, then you should make some modifications on top of SDK v 0.45.8

**Comment by faddat** [comment]
this is a highly impactful PR, performance-wise

**Comment by asalzmann** [comment]
I think this is resolved by https://github.com/Stride-Labs/stride/pull/301

**Pull request closed without merging**
