### PR TITLE
Certik july week1

### PR DESCRIPTION
**Pull request by riley-stride**
## Summary
Address findings from last week, please see the doc for details. Note that 4 (if changes are req'd) will come in a separate PR. Numbers 7 and 5 are waiting replies from CertiK.

## Reviewers (est ~30 min)
Check each commit to make sure it addresses the document from CertiK and that you agree with the change, then run the integration and unit tests

### CODE REVIEW

**Comment by asalzmann** [comment]
Is this ready for review?

**Comment by riley-stride** [comment]
> Is this ready for review?

Yes

**Review by asalzmann — APPROVED** [review]
lgtm

**Comment by asalzmann** [comment]
is this ready for merge?

**Pull request merged**
