### PR TITLE
remove uneeded casting, refractor transfer from mint

### PR DESCRIPTION
**Pull request by sontrinh16**
Closes: #422

## Context and purpose of the change

Fix some audited coding style 

## Author's Checklist

I have...

- [x] remove some unnecessary casting to uint64
- [x] remove some unnecessary else statement
- [ ] remove err check in RedeemStake
- [ ] Change type name for ReinvestAmount
- [x] Move send stCoins logic to LiquidStake instead of MintAsset

### CODE REVIEW

**Comment by sontrinh16** [comment]
i dont think we can remove the address err check in redeemstake and liquidstake without fixing the test cases right now

**Review by sampocs — COMMENTED** [review]
Thanks for opening this! I agree on moving the code out of the else statement. 

Can you elaborate on the motivation behind moving the transfer out of the mint function? If it's because the name is unclear, you could just rename it to `MintAndTransferStAsset`

**Comment by sontrinh16** [comment]
i think that function should only have 1 responsibility that is minting as it describe, the transfer should be moving out of the funtion. Hmmm but yeah rename it would be clearer too

**Review by asalzmann — APPROVED** [review]
lgtm

**Review by sampocs — APPROVED** [review]

**Comment by sontrinh16** [comment]
Base on 2 approves, i will merge the PR

**Pull request merged**
