### PR TITLE
Integration Test Linux Support

### PR DESCRIPTION
**Pull request by sampocs**
Closes: #XXX

## Context and purpose of the change
* Fixed integration tests for linux (tested on Ubuntu)

## Brief Changelog
* Added bats-core submodule
* Ran bats binary from submodule executable

## Author's Checklist
I have...

- [X] Run and PASSED locally all GAIA integration tests
- [ ] If the change is contentful, I either:
    - [ ] Added a new unit test OR 
    - [ ] Added test cases to existing unit tests
- [ ] OR this change is a trivial rework / code cleanup without any test coverage

If skipped any of the tests above, explain.

## Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] manually tested (if applicable)
- [ ] confirmed the author wrote unit tests for new logic
- [ ] reviewed documentation exists and is accurate

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes? 
  - [ ] Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`?
  - [ ] This pull request updates existing proto field values (and require a backend and frontend migration)? 
  - [ ] Does this pull request change existing proto field names (and require a frontend migration)?
  How is the feature or change documented? 
      - [ ] not applicable
      - [ ] jira ticket `XXX` 
      - [ ] specification (`x/<module>/spec/`) 
      - [ ] README.md 
      - [ ] not documented

### CODE REVIEW

**Comment by riley-stride** [comment]
Could you remind me the status on this - have we tested on Linux?

**Comment by sampocs** [comment]
Yup tested on Debian and Ubuntu VMs. And I'm spinning up an Arch Linux VM in GCP as we speak to try it with that as well

**Comment by riley-stride** [comment]
Very groovy. @TaltaM can you let me know whether you can pass the integration tests with this branch?

**Comment by sampocs** [comment]
@faddat @nghuyenthevinh2000 I'm having trouble setting up the arch linux VM. When you have a chance, can you two confirm these integration tests work for your machine?

Remember to update submodules first:
```
git submodule update --init --recursive
make start-docker build=sgjor
make test-integration-docker
```

**Comment by sampocs** [comment]
Closed as these changes were incorporated into #431

**Pull request closed without merging**
