### PR TITLE
add integration test gh action

### PR DESCRIPTION
**Pull request by asalzmann**
**Summary**
Run integration tests

**Test plan**

### CODE REVIEW

**Comment by riley-stride** [comment]
Is this ready for review?

**Comment by asalzmann** [comment]
nope - changed to draft

**Comment by asalzmann** [comment]
Cool to see the bot works. We should keep this open!

**Comment by riley-stride** [comment]
Bumping this, I recall you mentioning there was an issue with integrating these? I can jump in to help get it across the line too :)

**Pull request closed without merging**
