### PR TITLE
chore(dev-deps): upgrade ledger dependencies

### PR DESCRIPTION
**Pull request by keupsonite**
Please see:

- https://github.com/cosmos/cosmos-sdk/issues/18319
- https://github.com/cosmos/cosmos-sdk/issues/18423#issuecomment-1804129041

### CODE REVIEW

**Comment by keupsonite** [comment]
ping

**Review by riley-stride — APPROVED** [review]
lgtm, thanks for doing this

**Comment by keupsonite** [comment]
Hey @riley-stride, should I do something in order to fix or is unrelated to the PR?
Thanks

**Comment by sampocs** [comment]
@keupsonite was the test a gosec failure? If so, can you try and refresh your branch (pull in main) and I can re-run them

**Comment by keupsonite** [comment]
@sampocs Yes, I think so. I've updated the branch 🙏

**Comment by keupsonite** [comment]
@sampocs branch updated (again)

**Comment by sampocs** [comment]
Thanks @keupsonite!

**Pull request merged**
