### PR TITLE
chore: Migrate cosmos-sdk to v0.46.2

### PR DESCRIPTION
**Pull request by lehieuhust**
**What is the purpose of the change**

- Upgrade cosmos-sdk to v0.46.2
- Upgrade ibc-go to v5

**Brief Changelog**

- Upgrade cosmos-sdk to v0.46.2
- Upgrade ibc-go to v5

**Testing and Verifying**

- This change is a trivial rework/code cleanup without any test coverage

**Documentation and Release Note**

- Does this pull request introduces a new feature or user-facing behaviour changes? no
- How is the feature or change documented? not applicable

### CODE REVIEW

**Comment by levanhieuhust** [comment]
> How is this affected by the dragonberry patch?

I think we should not use 46 sdk

**Comment by faddat** [comment]
@levanhieuhust -- nice work on this. 

There was -- a lot-- of miscommunication around the dragon and 46.3.

I've spoken with Marko and he says it is good to go.  I am going to update this branch.

**Comment by levanhieuhust** [comment]
> @levanhieuhust -- nice work on this.
> 
> There was -- a lot-- of [miscommunication](https://forum.cosmos.network/t/ibc-security-advisory-dragonberry/7702/20) around the dragon and 46.3.
> 
> I've spoken with Marko and he says it is good to go. I am going to update this branch.
> 
> Actually, @levanhieuhust would you mind doing it, once ibc-go is updated to v0.46.3?
> 
> Thank you.

Thank Sir ! I'm willing to keep doing it when ibc-go is updated to v0.46.3

**Comment by faddat** [comment]
I refreshed this, but I think we should close in favor of #347

**Pull request closed without merging**
