### PR TITLE
Custom Module Consensus Versions

### PR DESCRIPTION
**Pull request by sampocs**
We should start with consensus version 1 for our custom modules. It will change to 2 when we do our first soft upgrade

### CODE REVIEW

**Review by riley-stride — APPROVED** [review]
Looks straightforward. Only Q: do we need to do the same for interchainquery and epochs?

**Comment by sampocs** [comment]
They're actually already at ConsensusVersion 1! All though more reason why we should change ours

**Comment by riley-stride** [comment]
> They're actually already at ConsensusVersion 1! All though more reason why we should change ours

Sweet let's merge it in!

**Review by vish-stride — APPROVED** [review]
very contentious but i'll approve

**Pull request merged**
